### ISSUE TITLE
Absence of Cursor Pointer on Brand-Logo

### ISSUE THREAD

**Issue by ayushsuryan** [soft-eng-practicum/AnalySim#46]

**Comment by cengique** [comment]
Fixed by 60debb2 [60debb2](https://github.com/soft-eng-practicum/AnalySim/commit/60debb209e0280f94a8e5f1dd743dedadf6b3d9a). Thank you @ayushsuryan !

**Comment by cengique** [comment]
@ayushsuryan email me if you want to apply to work on this project in the next [GSoC](https://summerofcode.withgoogle.com/) round.
